/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.sonarb;
import java.util.*;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Sonarb extends AbstractSonarb { 
	public Sonarb(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	
	public void initSonar(){
		doWorkSonarMock();
	}
	
	public void doWorkSonarMock(){
		new Timer().schedule(new TimerTask(){
			@Override
			public void run(){
				//emetto evento terminazione
				emit("data","distanza(B, d(42))");
				println("rover rilevato sulla linea d'arrivo");
			}
		},5000);
		/*try {
			Thread.sleep(9000);
			println("passati 9 s");
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		//emetto evento terminazione
		emit("data","distanza(B, d(42))");
		println("rover rilevato sulla linea d'arrivo");*/
	}
	
}
