/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.rilevatorearrivo;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Rilevatorearrivo extends AbstractRilevatorearrivo { 
	public Rilevatorearrivo(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
