/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.mocsonarb;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Mocsonarb extends AbstractMocsonarb { 
	public Mocsonarb(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
