/* Generated by AN DISI Unibo */ 
package it.unibo.ctxSonarArrivo;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxSonarArrivo  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxsonararrivo", "./srcMore/it/unibo/ctxSonarArrivo/m1.pl", 
		"./srcMore/it/unibo/ctxSonarArrivo/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
