/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRover;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxRover  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = "./srcMore/it/unibo/ctxRover";
	return QActorContext.initQActorSystem(
		"ctxrover", "./srcMore/it/unibo/ctxRover/m1.pl", 
		"./srcMore/it/unibo/ctxRover/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
