/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.mocsonara;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Mocsonara extends AbstractMocsonara { 
	public Mocsonara(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
